name: Test
on:
  push:
    branches:
      - 'main'
    paths:
      - 'src/**'
      - '*.js'
      - '*.json'
  pull_request: 
    branches:
      - 'main'
    paths:
      - 'src/**'
      - '*.js'
      - '*.json'
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20' # Use a Node.js version that supports ES Modules
          registry-url: 'https://registry.npmjs.org'

      - name: Install Dependencies
        run: yarn install

      - name: Run Tests
        run: yarn test

      - name: Build Package
        run: yarn build
