name: Generate Docs
on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Publish"]
    branches: [main]
    types: 
      - completed

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20' # Use a Node.js version that supports ES Modules
          registry-url: 'https://registry.npmjs.org'

      - name: Install Dependencies
        run: yarn install

      - name: Run Tests
        run: yarn test

      - name: Build Package
        run: yarn build

      - name: Create the docs directory locally in CI
        run: npx typedoc src/index.ts

      - name: Cache Docs
        id: docs-cache
        uses: actions/cache@v4
        with:
          path: docs
          key: nostr-geotags-docs
      
      - name: Change branch
        run: git checkout -f gh-pages

      - name: Restore Docs
        uses: actions/cache/restore@v3
        id: cache-restore
        with: 
          path: .
          key: nostr-geotags-docs
          fail-on-cache-miss: true

      - name: Push to gh-pages branch
        run: git commit -am "Update Docs @${{ hashFiles('docs') }} " && git push origin gh-pages

