name: Generate Docs
on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Publish"]
    branches: [main]
    types: 
      - completed

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20' # Use a Node.js version that supports ES Modules
          registry-url: 'https://registry.npmjs.org'

      - name: Install Dependencies
        run: yarn install

      - name: Run Tests
        run: yarn test

      - name: Build Package
        run: yarn build

      - name: TSDoc Action
        uses: erikyo/tsdoc-action@v1
        with:
          source_dir: ./src/*
          output_dir: ./docs
          front_page: README.md
      
      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: './docs'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2